@startuml

[*] --> IDLE

state "<b>IDLE</b>\n<i>Idle state awakened by start_strobe</i>" as IDLE
state "<b>START</b>\n<i>Sends start bit</i>" as START
state "<b>SEND_DATA</b>\n<i>Serializes 8bits of data to output line</i>" as SEND_DATA
state "<b>STOP</b>\n<i>Sends stop bit</i>" as STOP


IDLE        --> START: start_strobe
START       --> START: baud_count < cycles_per_bit
START       --> SEND_DATA: baud_count == cycles_per_bit
SEND_DATA   --> SEND_DATA: bit_count < BYTE_SIZE
SEND_DATA   --> STOP: bit_count == BYTE_SIZE
STOP        --> STOP: baud_count < cycles_per_bit
STOP        --> IDLE: baud_count == cycles_per_bit

@enduml