name: Verilog and Assembler CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-verilog-tests:
    name: Run Verilog Simulation Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python for Verilog Scripts
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Icarus Verilog, sv2v, and unzip
        run: |
          sudo apt-get update -y
          sudo apt-get install -y iverilog curl unzip
          SV2V_VERSION="v0.0.13"
          SV2V_ZIP_NAME="sv2v-Linux.zip"
          SV2V_ASSET_URL="https://github.com/zachjs/sv2v/releases/download/${SV2V_VERSION}/${SV2V_ZIP_NAME}"
          echo "Downloading sv2v ${SV2V_VERSION} zip from ${SV2V_ASSET_URL}..."
          curl -L "${SV2V_ASSET_URL}" -o /tmp/sv2v.zip
          echo "Unzipping sv2v..."
          mkdir -p /tmp/sv2v_extracted
          unzip -q /tmp/sv2v.zip -d /tmp/sv2v_extracted
          SV2V_BINARY_PATH="/tmp/sv2v_extracted/sv2v-Linux/sv2v"
          if [ -f "${SV2V_BINARY_PATH}" ]; then
              echo "sv2v binary found at ${SV2V_BINARY_PATH}"
              sudo mv "${SV2V_BINARY_PATH}" /usr/local/bin/sv2v
              sudo chmod +x /usr/local/bin/sv2v
              echo "sv2v installation complete. Version:"; sv2v --version
          else
              echo "ERROR: sv2v binary not found at ${SV2V_BINARY_PATH}."; ls -lR /tmp/sv2v_extracted; exit 1
          fi
          rm /tmp/sv2v.zip; rm -rf /tmp/sv2v_extracted

      - name: Make Verilog test scripts executable
        run: |
          chmod +x scripts/python/run_tests.py
          chmod +x scripts/python/assemble_test.py

      - name: Generate .hex fixtures for Verilog tests
        run: |
          echo "Generating .hex files for ISA tests..."
          find hardware/test/instruction_set -name '*_tb.sv' -print0 | while IFS= read -r -d $'\0' tb_file; do
            test_name=$(basename "${tb_file}" _tb.sv)
            echo "Assembling for: ${test_name}"
            python3 scripts/python/assemble_test.py --test-name "${test_name}" --sub-dir instruction_set 
          done
          
          echo "Generating .hex files for CPU Control tests..."
          find hardware/test/cpu_control -name '*_tb.sv' -print0 | while IFS= read -r -d $'\0' tb_file; do
            test_name=$(basename "${tb_file}" _tb.sv)
            echo "Assembling for: ${test_name}"
            python3 scripts/python/assemble_test.py --test-name "${test_name}" --sub-dir cpu_control
          done

          echo "Generating .hex files for Module tests (if any need .asm fixtures)..."
          find hardware/test/modules -name '*_tb.sv' -print0 | while IFS= read -r -d $'\0' tb_file; do
            test_name=$(basename "${tb_file}" _tb.sv)
            if [ -f "software/asm/src/${test_name}.asm" ]; then
              echo "Assembling for: ${test_name}"
              python3 scripts/python/assemble_test.py --test-name "${test_name}" --sub-dir modules
            else
              echo "No ASM file found for module test: ${test_name}, skipping assembly."
            fi
          done
          echo "Fixture generation complete."
          echo "Listing generated fixtures directory:"
          ls -R hardware/test/fixtures_generated/

      - name: Execute all Verilog tests
        run: |
          python3 scripts/python/run_tests.py

      - name: Upload Verilog test artifacts
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: verilog-test-artifacts-${{ github.run_id }}
          path: |
            test_report_all.txt
            test_run_all.log
            build/sim_run_all_temp/
          retention-days: 7

  run-assembler-tests:
    name: Run Python Assembler Tests
    runs-on: ubuntu-latest
    # This job is independent of run-verilog-tests

    defaults:
      run:
        working-directory: software/assembler # Default for run steps in this job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python for Assembler Tests
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Or your preferred Python version for the assembler

      - name: Install Python dependencies
        # This step runs from the project root to find requirements.txt
        working-directory: ${{ github.workspace }} 
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            echo "Found requirements.txt in project root. Installing..."
            pip install -r requirements.txt
          else
            echo "requirements.txt not found in project root. Installing pytest and pytest-cov directly."
            pip install pytest pytest-cov
          fi

      - name: Run Assembler Pytests with Coverage
        # This step runs from software/assembler (due to job default working-directory)
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term 

      - name: Upload Assembler Test Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: assembler-coverage-report-${{ github.run_id }}
          # Path is relative to GITHUB_WORKSPACE (repository root)
          path: software/assembler/coverage.xml 
          retention-days: 7